### ISSUE TITLE
erro ao abrir posição vendida com ordem stop #bug

### ISSUE THREAD

**Issue by vfranca** [vfranca/mtcli#12]
comando:
mt sell wing20 -p 116110 -v 1 -sl 116450 -tp 115790
saída:
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\sell.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python38\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python38\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python38\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python38\lib\site-packages\mtcli\cli.py", line 122, in sell
    res = trading.sell_stop(symbol, price, volume, stop_loss, take_profit)
  File "c:\python38\lib\site-packages\mtcli\trading.py", line 64, in sell_stop
    if res < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by vfranca** [comment]
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\sell.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python38\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python38\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python38\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python38\lib\site-packages\mtcli\cli.py", line 122, in sell
    res = trading.sell_stop(symbol, price, volume, stop_loss, take_profit)
  File "c:\python38\lib\site-packages\mtcli\trading.py", line 64, in sell_stop
    if res < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by vfranca** [comment]
Foi feita a correção e falta fazer testes em conta demo para finalizar
