### ISSUE TITLE
O comando mt positions -sl diferencia maiúscula e minúscula

### ISSUE THREAD

**Issue by vfranca** [vfranca/mtcli#14]
Se for digitado o ativo em minúscula o comando não encontra o ativo

**Comment by vfranca** [comment]
> position -s wing20 -sl 117220

Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\position.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python38\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python38\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python38\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python38\lib\site-packages\mtcli\cli.py", line 150, in positions
    res = trading.modify_stoploss(symbol, stop_loss)
  File "c:\python38\lib\site-packages\mtcli\trading.py", line 135, in modify_stoploss
    raise Exception("Não existe posição aberta para esse ativo!")
Exception: Não existe posição aberta para esse ativo!

**Comment by vfranca** [comment]
Foi feita a correção e falta fazer testes em conta demo para finalizar
