### ISSUE TITLE
#bug Égerado um erro ao executar o comando para alterar uma posição pelo ativo

### ISSUE THREAD

**Issue by vfranca** [vfranca/mtcli#16]
comando:
> mt positions -s wing20 -sl 116830
saída:
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\mt.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python38\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python38\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python38\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python38\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python38\lib\site-packages\mtcli\cli.py", line 188, in positions
    res = mt5.modify_position_symbol(symbol.upper(), stop_loss, 0.0)
  File "c:\python38\lib\site-packages\mtcli\mt5_facade.py", line 200, in modify_position_symbol
    raise Exception("Não existe posição aberta para esse ativo!")
Exception: Não existe posição aberta para esse ativo!

**Comment by vfranca** [comment]
foi corrigida  a pesquisa com caracteres capitalizados
